adapters:
  - http
  - webhook

enableVerify: true
verifyKey: yourVerifyKey  # 请修改这个验证密钥

adapterSettings:
  http:
    host: 0.0.0.0
    port: 8080
    cors: [*]

  webhook:
    destinations: 
    - 'http://localhost:8080/webhook' 