name: 定时发送QQ查寝消息

on:
  schedule:
    # 每天晚上22:40执行（UTC+8对应的是UTC+0的14:40）
    - cron: '40 14 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      
      - name: 设置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 运行发送脚本
        env:
          QQ_API_URL: ${{ secrets.QQ_API_URL }}
          QQ_API_TOKEN: ${{ secrets.QQ_API_TOKEN }}
          QQ_TARGETS: ${{ secrets.QQ_TARGETS }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENT_EMAIL: '13708435621@163.com'
          WORKFLOW_TRIGGER: ${{ github.event_name == 'workflow_dispatch' && 'manual' || 'schedule' }}
        run: python scripts/send_message.py 
